/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.authentication;

import config.MyConnection;
import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author eslim
 */
public class RegisterJFrame extends javax.swing.JFrame {

    /**
     * Creates new form RegisterJFrame
     */
    public RegisterJFrame() {
        initComponents();
        this.setTitle("BlueJeans - Registro");
        //Settung color in Jframe
        this.getContentPane().setBackground(Color.decode("#FAF7F2"));
        //Color Button
        RegisterDataButton.setBackground(Color.decode("#8E97FD"));
        BacktoLoginDataButton.setBackground(Color.decode("#03174D"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FirstNameTextField = new javax.swing.JTextField();
        LastNameTextField = new javax.swing.JTextField();
        EmailTextField = new javax.swing.JTextField();
        UsernameTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        PasswordField = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        RegisterDataButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        BacktoLoginDataButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        FirstNameTextField.setFont(new java.awt.Font("Cera Pro", 1, 14)); // NOI18N

        LastNameTextField.setFont(new java.awt.Font("Cera Pro", 1, 14)); // NOI18N

        EmailTextField.setFont(new java.awt.Font("Cera Pro", 1, 14)); // NOI18N

        UsernameTextField.setFont(new java.awt.Font("Cera Pro", 1, 14)); // NOI18N
        UsernameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameTextFieldActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Cera Pro", 1, 14)); // NOI18N
        jLabel1.setText("Ingreses sus nombres");

        jLabel2.setFont(new java.awt.Font("Cera Pro", 1, 14)); // NOI18N
        jLabel2.setText("Ingreses sus apellidos");

        jLabel3.setFont(new java.awt.Font("Cera Pro", 1, 14)); // NOI18N
        jLabel3.setText("Ingreses su correo electronico");

        jLabel4.setFont(new java.awt.Font("Cera Pro", 1, 14)); // NOI18N
        jLabel4.setText("Ingreses su contraseña");

        jLabel5.setFont(new java.awt.Font("Cera Pro", 1, 14)); // NOI18N
        jLabel5.setText("Ingreses su nombre de usuario");

        PasswordField.setFont(new java.awt.Font("Cera Pro", 1, 14)); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/Character_register.png"))); // NOI18N

        RegisterDataButton.setFont(new java.awt.Font("Cera Pro", 1, 14)); // NOI18N
        RegisterDataButton.setForeground(new java.awt.Color(255, 255, 255));
        RegisterDataButton.setText("Guardar");
        RegisterDataButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterDataButtonActionPerformed(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/bluejeans-preview.png"))); // NOI18N

        BacktoLoginDataButton.setFont(new java.awt.Font("Cera Pro", 1, 14)); // NOI18N
        BacktoLoginDataButton.setForeground(new java.awt.Color(255, 255, 255));
        BacktoLoginDataButton.setText("Volver al Login");
        BacktoLoginDataButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BacktoLoginDataButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 216, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(RegisterDataButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PasswordField)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(FirstNameTextField)
                    .addComponent(EmailTextField)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(LastNameTextField)
                    .addComponent(jLabel3)
                    .addComponent(UsernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BacktoLoginDataButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(100, 100, 100))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(53, 53, 53)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FirstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(UsernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(RegisterDataButton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(BacktoLoginDataButton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void UsernameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameTextFieldActionPerformed

    private void RegisterDataButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterDataButtonActionPerformed
        // TODO add your handling code here:
        String firstname = FirstNameTextField.getText();
        String lastname = LastNameTextField.getText();
        String email = EmailTextField.getText();
        String username = UsernameTextField.getText();
        String password = String.valueOf(PasswordField.getPassword());
        
        //Validaciones
        if(email.equals("")){
            JOptionPane.showMessageDialog(null, "El campo correo electronico es requerido");
        }else if(username.equals("")){
            JOptionPane.showMessageDialog(null, "El campo usuario es requerido");
        }else if(password.equals("")){
            JOptionPane.showMessageDialog(null, "El campo contraseña es requerido");
        }else{
            PreparedStatement ps;
        
            String query = "INSERT INTO users (firstname,lastname,email,username,password) VALUES (?,?,?,?,?)";

            try {
                ps = MyConnection.getConnection().prepareStatement(query);

                ps.setString(1, firstname);
                ps.setString(2, lastname);
                ps.setString(3, email);
                ps.setString(4, username);
                ps.setString(5, password);

                if(ps.executeUpdate() > 0){
                    JOptionPane.showMessageDialog(null, "Usuario creado con éxito");
                }
            } catch (SQLException ex) {
                Logger.getLogger(RegisterJFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_RegisterDataButtonActionPerformed

    private void BacktoLoginDataButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BacktoLoginDataButtonActionPerformed
        // TODO add your handling code here:
        LoginJFrame frameLogin = new LoginJFrame();
        frameLogin.setVisible(true);
        dispose();
    }//GEN-LAST:event_BacktoLoginDataButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BacktoLoginDataButton;
    public javax.swing.JTextField EmailTextField;
    public javax.swing.JTextField FirstNameTextField;
    public javax.swing.JTextField LastNameTextField;
    public javax.swing.JPasswordField PasswordField;
    public javax.swing.JButton RegisterDataButton;
    public javax.swing.JTextField UsernameTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
